sudo: required
services:
  - docker

install:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml build
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d redis postgres

jobs:
  include:
    - stage: 'Tests'
      name: 'Test API'
      script: docker-compose -f docker-compose.yml -f docker-compose.test.yml up api
