version: '3'

services:
  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=PROD
      - PORT
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/data/db

volumes:
  postgresdata:
