version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=PROD
      - PORT
      - JWT_SECRET
      - MAILER_EMAIL
      - MAILER_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
    links:
      - postgres
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgresdata:/data/postgres
  redis:
    image: bitnami/redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redisdata:/data/redis

volumes:
  postgresdata:
  redisdata: